### ISSUE TITLE
Test svg file

### ISSUE THREAD

**Issue by blueciren** [EmmaSchwarz/computational-dostoevsky#19]
1. Issue with errors in variable declarations

2. how to put two different attributes from xml document in the axis, using variables and for-each-group functions
[Golyadkin_test_voices.txt](https://github.com/EmmaSchwarz/computational-dostoevsky/files/4467656/Golyadkin_test_voices.txt)

**Comment by djbpitt** [comment]
@blueciren 

**Variable declaration:** When you open your *Golyadkin_test_voices.xsl* XSLT file, \<oXygen/\>tells you what’s wrong with the variable declaration. Look at the error message at the bottom of the screen. If you can’t figure it out, please follow up, but the place to start debugging is with the error message.

**Attributes and axes:** I can’t understand from the way you describe the task above what you need to do, and there are no comments in the XSLT. Which attributes, which axes, what type of graph, and what story do you want it to tell?

We’ll split into breakout rooms in class on Monday and I’ll be happy to go over it with you then, but before that, 1) try to debug the variable declaration problem, starting with the \<oXygen/> error message; 2) add some comments to the XSLT that describe what it does where (or what you would like it to do where); and 3) add a comment to this issue to explain the task in more detail.

**Comment by blueciren** [comment]
I am sorry I did not include what the error message appeared: it was "variable has not been declared," which I could not find why since I had a well-formed declaration. But when I closed and re-open the oxygen, it miraculously fixed the problem.

**Comment by djbpitt** [comment]
@blueciren When I open *Golyadkin\_test\_voices.xsl* in \<oXygen/\>, the error message says:

> expected ")", found "<eof>"

It doesn't say "variable has not been declared". Have you pushed the same version of the file as the one you are working on?

**Comment by blueciren** [comment]
I have no idea, but before I pushed the file, it said that the variable has not been declared, which made me really confused. That message popped up because I forgot to put ```)```, which I could solve it easily.  When I restarted the oxygen, it was automatically fixed and showed the green box.

**Comment by djbpitt** [comment]
@blueciren Can you push the fixed version? The one I pulled from the repo was missing the parenthesis, and when I pulled again just now, there wasn’t a newer version.

If you can comment the XSLT to explain what each section is supposed to do, and push that version, we can look at it together during the breakout session on Monday.

**Comment by blueciren** [comment]
I pushed it with additional comments. Thanks

**Comment by djbpitt** [comment]
Fixed. Closing.
