### ISSUE TITLE
Test Bubble File 

### ISSUE THREAD

**Issue by blueciren** [EmmaSchwarz/computational-dostoevsky#20]
Dear David,
Could you check the bubble graph file in development? I have two questions about bringing the texts into the both axes.

**Comment by djbpitt** [comment]
@blueciren I'm in the middle of dinner now, but I'll pull after that and then send you a Kakao message to arrange to discuss your questions over Zoom. Maybe around 8:45 p.m.?

**Comment by blueciren** [comment]
Sure. Please send me the message.

**Comment by djbpitt** [comment]
Closing issue. Resolved a is labels.
